In [1]:
import numpy as np

A= np.random.random((3,4))
B= np.random.random((3,3))
D= A.T;
X= A @ D
C = (X-B)
print(C)

A= np.array([[2,3,6,7,4],[3,5,7,9,10 ],[6,7,8,9,12]])

print(A)

print(A[-1:,-3:-2])

[[1.42332346 1.39804805 1.03025676]
 [1.34081696 0.63828151 0.30711952]
 [0.41295075 0.43172776 0.5206911 ]]
[[ 2  3  6  7  4]
 [ 3  5  7  9 10]
 [ 6  7  8  9 12]]
[[8]]
